const individuals = [
  {
    id: 1,
    name: 'Dr. Arbind Rout',
    degree: 'D.Litt',
    position: 'Professor',
    department: '',
    institution: 'NIMS University',
    country: 'India',
  },
  {
    id: 2,
    name: 'Sudheer Kumar Shriramoju',
    degree: '',
    position: 'Project Manager',
    department: '',
    institution: 'Wipro InfoTech',
    country: 'India',
  },
  {
    id: 3,
    name: 'Sotvoldiev Nodirbek Jurabaevich',
    degree: 'Doctor of Sciences in Economics (DSc)',
    position: 'Associate Professor',
    department: '',
    institution: 'Namangan State University',
    country: 'Uzbekistan',
  },
  {
    id: 4,
    name: 'Niravkumar Dhameliya',
    degree: '',
    position: 'Software Engineer',
    department: '',
    institution: 'Health Advocate',
    country: 'USA',
  },
  {
    id: 5,
    name: 'Bhagya Rekha Kalukurthi',
    degree: '',
    position: 'R&D Engineer3',
    department: '',
    institution: 'Broadcom Inc',
    country: 'India',
  },
  {
    id: 6,
    name: 'Malyadri K',
    degree: '',
    position: 'Micro Services Lead Developer',
    department: '',
    institution: 'CGI at Client PNC',
    country: 'USA',
  },
  {
    id: 7,
    name: 'Vali Raximdjanovich Khodjibaev',
    degree: 'Doctor of Sciences in Physics and Mathematics (DSc)',
    position: 'Professor',
    department: '',
    institution: 'Namangan Engineering Construction Institute',
    country: 'Uzbekistan',
  },
  {
    id: 8,
    name: 'Satya Nagendra Prasad Poloju',
    degree: '',
    position: 'Sr SAP Data & Analytics Specialist',
    department: '',
    institution: 'Rumpke Waste & Recycling',
    country: 'USA',
  },
  {
    id: 9,
    name: 'Sriharsha Vinjamury',
    degree: '',
    position: 'Principal Test Engineer, SOPT',
    department: '',
    institution: 'ARM Inc',
    country: 'USA',
  },
  {
    id: 10,
    name: 'Prof. G. Sathishkumar',
    degree: '',
    position: 'Associate Professor',
    department: 'NIMS School of Business',
    institution: 'NIMS University',
    country: 'India',
  },
  {
    id: 11,
    name: 'Dr. Sneha H. Bhalala (PT)',
    degree: 'MPT - Pediatrics',
    position: 'Assistant Professor',
    department: '',
    institution: 'SPB Physiotherapy College',
    country: 'India',
  },
  {
    id: 12,
    name: 'Normatova Muborak Jabborovna',
    degree: 'Doctor of Philosophy (PhD)',
    position: '',
    department: '',
    institution: 'Navoi State Mining Institute',
    country: 'Uzbekistan',
  },
  {
    id: 13,
    name: 'Ergashev Ilxom Yuldashevich',
    degree: 'Doctor of Philosophy (PhD)',
    position: '',
    department: '',
    institution: 'Navoi State Mining Institute',
    country: 'Uzbekistan',
  },
  {
    id: 14,
    name: 'Raxmatov Safarboy Xudoyberdiyevich',
    degree: 'Doctor of Philosophy (PhD)',
    position: '',
    department: '',
    institution: 'Navoi State Mining Institute',
    country: 'Uzbekistan',
  },
  {
    id: 15,
    name: 'Govinda Rao Banothu',
    degree: '',
    position: 'SAP Analytics Cloud Technical Specialist',
    department: '',
    institution: 'Fusion Plus Solutions Inc.',
    country: 'USA',
  },
  {
    id: 16,
    name: 'Raximov Ilhomjon Abdullaevich',
    degree: 'Doctor of Philosophy on pedagogical sciences (PhD)',
    position: 'Associate Professor',
    department: '',
    institution: 'Namangan State University',
    country: 'Uzbekistan',
  },
  {
    id: 17,
    name: 'Egamberdiev Bakhrom Egamberdievich',
    degree: '',
    position: 'Professor',
    department: '',
    institution:
      'Scientific Research Institute of Semiconductor Physics and Microelectronics at the National University of Uzbekistan',
    country: 'Uzbekistan',
  },
  {
    id: 18,
    name: 'Makhmudova Sevara Irisaliyevna',
    degree: 'Doctor of Philosophy (Ph.D.) in Philological Sciences',
    position: 'Associate Professor',
    department: 'Department of Uzbek Language and Literature',
    institution: 'Uzbek State Institute of Arts and Culture',
    country: 'Uzbekistan',
  },
  {
    id: 19,
    name: 'Fayziboyev Pirmamat Normamatovich',
    degree: 'Doctor of Philosophy in Medical Sciences (Ph.D.)',
    position: 'Associate Professor',
    department: 'General Hygiene and Ecology',
    institution: 'Samarkand State Medical Institute',
    country: 'Uzbekistan',
  },
  {
    id: 20,
    name: 'Prof. (Ar.) Riya Richard Shawel',
    degree: '',
    position: '',
    department: 'Institute of Architecture',
    institution: 'Sage University',
    country: 'India',
  },
  {
    id: 21,
    name: 'Xoliyarov Musadilla Shodievich',
    degree: 'Doctor of Philosophy Ph.D on technics',
    position: 'Head of the department of Education Quality Control',
    department: '',
    institution: 'Tashkent Institute of Textile and Light Industry',
    country: 'Uzbekistan',
  },
  {
    id: 22,
    name: 'Ergasheva Guzal Kurbonalievna',
    degree: 'Doctor of Philosophy in Philological Sciences (PhD)',
    position: '',
    department: '',
    institution: 'Uzbekistan State World Languages University',
    country: 'Uzbekistan',
  },
  {
    id: 23,
    name: 'Gafurov Adham Anvarovich',
    degree: 'Doctor of Medical Sciences',
    position: 'Professor',
    department: "Department of Children's Surgery",
    institution: 'Andijan State Medical Institute',
    country: 'Uzbekistan',
  },
  {
    id: 24,
    name: 'Jumayeva Zulkhumor Ergashevna',
    degree: 'PhD in Technics',
    position: '',
    department: '',
    institution: 'Termiz State University',
    country: 'Uzbekistan',
  },
  {
    id: 25,
    name: 'Nazarov Jamoliddin Toshkulovich',
    degree: 'Doctor of Philosophy (PhD)',
    position: '',
    department: '',
    institution: 'Navoi State Mining Institute',
    country: 'Uzbekistan',
  },
  {
    id: 26,
    name: 'Bozorova Nayima Xudayberdiyevn',
    degree: 'Doctor of Philosophy (Ph.D.) Technical Sciences',
    position: 'Head of the Department of Special Sciences',
    department: '',
    institution: 'Yangiyer branch of the Tashkent Institute of Chemical Technology',
    country: 'Uzbekistan',
  },

  {
    id: 28,
    name: 'Anitha Eemani',
    degree: '',
    position: 'Sr. Java Full Stack Developer',
    department: '',
    institution: 'National Association of Insurance Commissioners (NAIC)',
    country: 'USA',
  },
  {
    id: 29,
    name: 'Manav Mittal',
    degree: '',
    position: '',
    department: '',
    institution: 'Administrative Controls Management Inc.',
    country: 'Michigan, USA',
  },
  {
    id: 30,
    name: 'Xasanova Mukharrama Almaredanovna',
    degree: 'Doctor of Philosophy (PhD)',
    position: 'Associate Professor',
    department: 'Department of Forensic Medicine and Medical Law',
    institution: 'Tashkent Medical Academy',
    country: 'Uzbekistan',
  },
  {
    id: 31,
    name: "Tursunova Iroda Ne'matovna",
    degree: 'Doctor of Philosophy (PhD)',
    position: '',
    department: '',
    institution: 'Navoi State Mining Institute',
    country: 'Uzbekistan',
  },
  {
    id: 32,
    name: 'Azizova Pakiza Khusanovna',
    degree: 'Doctor of Philosophy (PhD)',
    position: 'Associate Professor',
    department: 'Department of Internal Diseases-2 and Endocrinology',
    institution: 'Tashkent Medical Academy',
    country: 'Uzbekistan',
  },
  {
    id: 33,
    name: 'Toshmatova Guzal Adilxodjaevna',
    degree: 'Doctor of Philosophy (PhD)',
    position: '',
    department: '',
    institution: 'Tashkent Medical Academy',
    country: 'Uzbekistan',
  },
  {
    id: 34,
    name: 'Sagdullayeva Dilafruz Saidakbarovna',
    degree: 'Doctor of Technical Sciences (Ph.D.)',
    position: 'Senior Researcher',
    department: 'Institute of Bioorganic Chemistry of the Academy of Sciences',
    institution: 'Republic of Uzbekistan',
  },
  {
    id: 35,
    name: 'Otajonov Ilkhom Otaboevich',
    degree: 'Doctor of Sciences (DSc)',
    position: '',
    department: '',
    institution: 'Tashkent Medical Academy',
    country: 'Uzbekistan',
  },
  {
    id: 36,
    name: 'Dr. Fayzullaev Shavkat Raimovich',
    degree: '',
    position: 'Docent of the Department',
    department: 'Spinning Technology',
    institution: 'Tashkent Institute of Textile and Light Industry',
    country: 'Uzbekistan',
  },
  {
    id: 37,
    name: 'Vivek Thoutam',
    degree: '',
    position: 'Researcher, Senior Python Developer',
    department: '',
    institution: '',
    country: 'California, USA',
  },
  {
    id: 38,
    name: 'Xamzayev Akbar Abdualimovich',
    degree: 'Doctor of Philosophy (PhD)',
    position: '',
    department: '',
    institution: 'Navoi State Mining Institute',
    country: 'Uzbekistan',
  },
  {
    id: 39,
    name: 'Ilkhom Kholmuminovich Amanturdiev',
    degree: 'Doctor of Philosophy (Ph.D.) Agricultural Sciences',
    position: '',
    department: '',
    institution: 'Samarkand branch of Tashkent State Agrarian University',
    country: 'Uzbekistan',
  },
  {
    id: 40,
    name: 'Sriram K. Bhagavathula',
    degree: '',
    position: 'Sr. Director Analytics',
    department: '',
    institution: 'Cinnamon Bay Servicing',
    country: 'St. Thomas, US Virgin Islands',
  },
  {
    id: 41,
    name: 'Nasrullah Abbasi',
    degree: '',
    position: 'AI-Healthcare Researcher',
    department: '',
    institution: 'Washington University of Science and Technology',
    country: 'Alexandria, VA, USA',
  },

  {
    id: 43,
    name: 'Mohammed Kholmuminovich',
    degree: 'Doctor of Philosophy (Ph.D.) in Agricultural Sciences',
    position: '',
    department: '',
    institution: 'Samarkand branch of Tashkent State Agrarian University',
    country: 'Uzbekistan',
  },
  {
    id: 44,
    name: 'Togaeva Sarvinoz Suyunovna',
    degree: 'Doctor of Philosophy (Ph.D.) in Agriculture',
    position: 'Associate Professor',
    department: 'Department of Plant Science and Oilseed Crops',
    institution: 'Tashkent State Agrarian University',
    country: 'Uzbekistan',
  },
  {
    id: 45,
    name: 'Matnazarova Gulbaxor Sultanovna',
    degree: 'Doctor of Medical Science (DSc)',
    position: '',
    department: '',
    institution: 'Tashkent Medical Academy',
    country: 'Uzbekistan',
  },
  {
    id: 46,
    name: 'Manoj Bhoyar',
    degree: '',
    position: 'Technology Manager',
    department: '',
    institution: 'Bank of America',
    country: 'New Jersey, USA',
  },
  {
    id: 47,
    name: 'Siva Prasad Patnayakuni',
    degree: '',
    position: 'Senior Data Engineer',
    department: '',
    institution: 'H-E-B',
    country: 'Texas, USA',
  },
  {
    id: 48,
    name: 'Abdukaxarova Muattarhon Fahritdinovna',
    degree: 'Doctor of Philosophy (PhD)',
    position: '',
    department: '',
    institution: 'Tashkent Medical Academy',
    country: 'Uzbekistan',
  },
  {
    id: 49,
    name: 'Jurayev Sherali Sharipovich   ',
    degree: 'Candidate of Technical Sciences (Ph.D.)',
    position: 'Associate Professor',
    department: '',
    institution: 'Namangan Engineering Construction Institute',
    country: 'Uzbekistan',
  },
  {
    id: 50,
    name: 'Negmatov Mirzobaxram Karimovich',
    degree: 'Candidate of Technical Sciences (Ph.D.)',
    position: 'Associate Professor',
    department: '',
    institution: 'Namangan Engineering Construction Institute',
    country: 'Uzbekistan',
  },
  {
    id: 51,
    name: 'Nishonov Fayzullo Xolmirzayevich',
    degree: 'Candidate of Technical Sciences (Ph.D.)',
    position: 'Associate Professor',
    department: '',
    institution: 'Namangan Engineering Construction Institute',
    country: 'Uzbekistan',
  },
  {
    id: 52,
    name: 'Mukhamedov Djabirkhon',
    degree: '',
    position: 'Professor of General Technical Sciences',
    department: '',
    institution: 'Namangan Engineering and Construction Institute',
    country: 'Uzbekistan',
  },
  {
    id: 53,
    name: 'Abdurahimov Shavkatjon Olimovich',
    degree: 'Candidate of Agricultural Sciences',
    position: 'Associate Professor',
    department: 'Department of Land and Melioration',
    institution: 'Tashkent State Agrarian University',
    country: 'Uzbekistan',
  },
  {
    id: 54,
    name: 'Sultanov Umbetali Tazabayevich',
    degree: 'Doctor of Philosophy (Ph.D.) in Agricultural Sciences',
    position: 'Associate Professor',
    department: 'Department of Land and Melioration',
    institution: 'Tashkent State Agrarian University',
    country: 'Uzbekistan',
  },
  {
    id: 55,
    name: 'Sudheer Devaraju',
    degree: 'Master of Science (Software Engineering)',
    position: 'Staff Solutions Consultant & Applied Researcher',
    department: '',
    institution: 'Walmart Labs',
    country: 'Bentonville, AR, USA',
  },
  {
    id: 56,
    name: 'Nandakumar Ramachandran Pezhery',
    degree: '',
    position: 'Vice President - Cloud Technology Solutions',
    department: '',
    institution: 'Xoriant Inc',
    country: 'New Jersey, USA',
  },
  {
    id: 57,
    name: 'Rakesh Rojanala',
    degree: '',
    position: 'Senior Manager',
    department: '',
    institution: 'GENPACT',
    country: 'India',
  },
  {
    id: 58,
    name: 'Dr. Chokkamreddy Prakash',
    degree: '',
    position: 'Assistant Professor',
    department: 'School of Management Studies',
    institution: 'Guru Nanak Institutions Technical Campus',
    country: 'Hyderabad, India',
  },
  {
    id: 59,
    name: 'Dr. V. Revathy',
    degree: '',
    position: 'Associate Professor in Nursing',
    department: 'Department of Child Health Nursing',
    institution: 'Mother Theresa Post Graduate & Research Institute of Health Sciences',
    country: 'Puducherry, India',
  },
  {
    id: 60,
    name: 'Ravi Prasad Ravuri',
    degree: '',
    position: 'Application Developer',
    department: '',
    institution: 'Sriven Technologies',
    country: 'Ashburn, Virginia, USA',
  },
  {
    id: 61,
    name: 'Sherqulov O’ktam Dehqonovich',
    degree: 'Doctor of Philosophy (PhD)',
    position: 'Dotsent',
    department: '',
    institution: 'Navoi State Pedagogical Institute',
    country: 'Uzbekistan',
  },
  {
    id: 62,
    name: 'Brij Kishore Pandey',
    degree: '',
    position: 'Principal Application Developer',
    department: '',
    institution: 'ADP',
    country: 'Parsippany, NJ, USA',
  },
  {
    id: 63,
    name: 'Maria Anurag Reddy Basani',
    degree: 'Sr. Data Engineer',
    position: 'Sr. Data Engineer',
    institution: 'USA',
    country: 'USA',
  },
  {
    id: 64,
    name: 'Srinivas Murri',
    degree: 'Lead Data Engineer',
    position: 'Lead Data Engineer',
    institution: 'WA, USA',
    country: 'USA',
  },
  {
    id: 65,
    name: 'Jamilov Yusuf Yunus Ugli',
    degree: 'Doctor of Philosophy in Pedagogical Sciences (PhD)',
    position: "Teacher of the Department 'Pedagogy, Psychology and Technological Education'",
    institution: 'Pedagogical Institute of Bukhara State University',
    country: 'Uzbekistan',
  },
  {
    id: 66,
    name: 'Juraev Akmal Razzokovich',
    degree: 'Associate Professor, Doctor of Philosophy (PhD) in Pedagogical Sciences',
    position: 'Professor, Dean of the Faculty of Pedagogical Education',
    institution: 'Pedagogical Institute of Bukhara State University',
    country: 'Uzbekistan',
  },
  {
    id: 67,
    name: 'Boltayev Zafar Ikhtiyorovich',
    degree: 'Doctor of Physical and Mathematical Sciences (DSc)',
    position: "Associate Professor of the Department 'Higher Mathematics'",
    institution: 'Bukhara Institute of Engineering and Technology',
    country: 'Uzbekistan',
  },
  {
    id: 68,
    name: 'Ochilov Shokir Baxtiyarovich',
    degree: 'Doctor of Philosophy (Ph.D.) Pedagogical Sciences',
    position: 'Navoi State Pedagogical Institute',
    institution: 'Navoi State Pedagogical Institute',
    country: 'Uzbekistan',
  },
];
